spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=oba;encrypt=true;trustServerCertificate=true
    username: sa
    password: ${db.pass}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.xml
    contexts: hom

---

spring:
  config.activate.on-profile: server
  liquibase:
    enabled: false
