spring:
  application:
    name: aplicacao-liquibase

  # Configuração comum a todos os perfis
  liquibase:
    change-log: classpath:db/db.changelog-master.xml

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
      url: jdbc:sqlserver://localhost:1433;databaseName=oba;encrypt=true;trustServerCertificate=true
      username: sa
      password: ${db.pass}
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  liquibase:
    enabled: true
    contexts: dev

---

spring:
  config:
    activate:
      on-profile: homol

  datasource:
      url: jdbc:sqlserver://localhost:1433;databaseName=oba;encrypt=true;trustServerCertificate=true
      username: sa
      password: ${db.pass}
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  liquibase:
    enabled: true
    contexts: homol

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=banco_prod;encrypt=true;trustServerCertificate=true
    username: sa
    password: ${db.pass}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  liquibase:
    enabled: false
